In [24]:
#Q1
import numpy as np
from scipy.spatial.distance import cdist
from sklearn.metrics import mean_squared_error as mse

def kmeans(X, k, dim):
    Centers = np.random.random((k,dim)) * X.max()
    Centers_2 = np.zeros((K, dim)) 
    imax = 100
    i=0
    
    while (Centers != Centers_2).all() and i<imax:
        Centers_2 = np.copy(Centers)
        clusters = np.zeros((k,X.shape[0]))
        dist_min = np.zeros((k,X.shape[0]))
        clusters = cdist(Centers,X)
        dist_min = np.argmin(clusters,0)
        Centers = np.array([np.mean(X[dist_min == j, :],0) for j in range(k)])
        i += 1

    if (Centers != Centers_2).all() and i>=imax:
        Centers = data[:k,:dim]
       
    return Centers, dist_min

In [27]:
#Q2
k = 3
data = np.loadtxt("iris.data",delimiter = ',',usecols=range(0,2))
print "Prueba con las dos primeras dimensiones del dataset iris"
print ""

dim = 2
X = data[:,:dim]
Cent,dist_min = kmeans(X, k, dim)
print "Centroides: "
print Cent
print ""

y_pred = np.array([Cent[dist_min[i],:] for i in range(data.shape[0])]) 

print "MSE:", mse(X,y_pred)


for y in range(k):
    
    if X[dist_min==y,:].any():
        print "El MSE del cluster", y, "es:", mse(X[dist_min==y,:],y_pred[dist_min == y,:])

data = np.loadtxt("iris.data",delimiter = ',',usecols=range(0,4))
print "Prueba con 4 dimensiones del dataset iris"
print ""

dim = 4
X = data[:,:dim]
Cent, dist_min = kmeans(X, k, dim)
print "Centroides: "
print Cent
print ""

y_pred = np.array([Cent[dist_min[i],:] for i in range(data.shape[0])]) 

print "El MSE global es:", mse(X,y_pred)

for y in range(k):
    
    if X[dist_min==y,:].any():
        print "El MSE del cluster", y, "es:", mse(X[dist_min==y,:],y_pred[dist_min == y,:])


Prueba con las dos primeras dimensiones del dataset iris

Centroides: 
[[ 5.1  3.5]
 [ 4.9  3. ]
 [ 4.7  3.2]]

MSE: 0.880333333333
El MSE del cluster 1 es: 0.880333333333
Prueba con 4 dimensiones del dataset iris

Centroides: 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]

El MSE global es: 2.99806666667
El MSE del cluster 1 es: 2.99806666667
